import { createSlice } from "@reduxjs/toolkit";

const initialState = {
    value: []
  };

export const shoppingCartSlice = createSlice({
    name: 'shoppingCart',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
      add: (x, state , payload) => {
            alert(x)
      }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
  });
  
  export const { add } = shoppingCartSlice.actions;

  export const shoppingCartReducer =  shoppingCartSlice.reducer;