import { createSlice } from "@reduxjs/toolkit";


const initialState = {
    value: []
  };

export const shoppingCartSlice = createSlice({
    name: 'shoppingCart',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
      add: (state, action) => {
            state.value.push({...action.payload, qty:1})
      }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
  });
  
  export const { add } = shoppingCartSlice.actions;

  export const shoppingCartReducer =  shoppingCartSlice.reducer;